#!/bin/bash
##########################################

#Author: Sichun(Victor) Yin
#This bash file exports the data stored in 
#the database(argument 1) into csv files

##########################################

if [ "$1" = "" ]
then
	echo "You must enter the name of the database. Please check the README."
	exit 1
fi

mkdir -p $PWD/data  #check/create a new directory named data
cp -av $1 $PWD/data   #copy the database into the directory
cd data
db=$1

t=($(sqlite3 $db ".tables"))

for i in "${t[@]}"
do
	sqlite3 $db<<- EXIT_HERE
	.mode csv
	.headers on
	.output $i.csv
	SELECT * FROM $i;
	.exit
	EXIT_HERE
  echo "$i.csv generated"
done
